### PR TITLE
Chore: Added gatsby-V2 site demo

### PR DESCRIPTION
**Pull request by erichodges**
Hi Swizec,
[https://chakra-ui-test-delta.now.sh/](url)
Here's a demo Gatsby site I made for useAuth. It's not quite finished, but I think it's far enough along for you to get an idea of the direction. I'm happy to finish it with your guidance. 

Best,

Eric

### CODE REVIEW

**Comment by Swizec** [comment]
Wow this is amazing! I feel terrible for missing this PR for ... 3 months 🙈

What is different in the integration between this and the existing gatsby example? I think they're both using Gatsby v2?

**Comment by Swizec** [comment]
Do you mind if I use this for an official docs page?

**Comment by erichodges** [comment]
Hi @Swizec,
Please use it if you want. I have built another gatsby site using theme-ui though. I could use that as a starter and integrate the work I did on this project into that. If you want to look at the other site, let me know and I'll send you the URL.

**Comment by Swizec** [comment]
Gonna merge this for now, would love to see the other site @erichodges :)

**Comment by Swizec** [comment]
@all-contributors add @erichodges for code

**Comment by erichodges** [comment]
@Swizec 
Re: "What is different in the integration between this and the existing gatsby example? I think they're both using Gatsby v2?"

IIRC, 
I started a fresh gatsby site
followed your docs for useAuth
set up a new account on Auth0
setup Chakra UI
setup a bunch of things for mdx files
setup the docs as mdx files
did the Chakra UI styling

That's why it's very different from your docs site.

**Comment by Swizec** [comment]
Gotcha, thanks for the awesome work! I was worried you had to change something about the useAuth integration itself ^_^

**Comment by erichodges** [comment]
You're welcome. I hope you can use it. It will be good for my portfolio :-). Let me know if you need me to do something.

**Pull request merged**
