### PR TITLE
Start in authenticating state

### PR DESCRIPTION
**Pull request by oyvinmar**
The main change suggested in this PR is to start in the `isAuthenticating` state. I have updated the create-react-app example to show a use-case for this change. In the example I've added a PrivateRoute component to handle routes which should only be visible to logged in users. As you may see the logic will fail if both `isAuthenticating` and `isAuthenticated()` is false in the first render.

The second change is to return an error object form useAuth if present. Typically we want to send the user to a login page if they are not authenticated, but this may result in a redirect loop if an error occurs. By exposing the error object we can prevent this.

### CODE REVIEW

**Comment by oyvinmar** [comment]
@Swizec Any chance you can take a look at this? Currently using a forked version with the changes but it would be nice to get it merged.

**Comment by pekzanan** [comment]
Any chance to merge this awesome PR?

**Comment by huntedman** [comment]
My SPA would also benefit from this PR. Currently there is no straightforward way to display authentication errors to the user.

**Comment by dmi3y** [comment]
This is something I stumbled upon as well, would be nice to have it merged indeed 👍

**Comment by tsaiDavid** [comment]
@Swizec - is there anything we can do to help?

**Pull request closed without merging**
