### PR TITLE
adding example with create-react-app

### PR DESCRIPTION
**Pull request by dejanstrancar**
Adding requested example without using Gatsby, but create-react-app instead. The only difference to original create-react-app configuration is that its running on port 8000 instead 3000, due to auth0 callback is locked to port 8000.

### CODE REVIEW

**Comment by converge** [comment]
super cool idea! I would like to contribute on the PR also.

**Comment by gregjoeval** [comment]
Thanks for the example! Just a suggestion but, it might be helpful to leave a note in the ReadMe that you can configure the Auth0 settings to allow port 3000 (the default port for create-react-app), or any other port for that matter

**Comment by Swizec** [comment]
@gregjoeval but you can't yet :P

I think that's the other currently open PR

**Comment by Swizec** [comment]
@all-contributors add @dejanstrancar for example

**Comment by Swizec** [comment]
Good point @gregjoeval port 3000 should work. I checked the code again and it isn't hardcoded anywhere (other than as a default).

My default Auth0 app that this example uses, however, _is_ set to `localhost:8000`. Updating it now to allow 3000 as well :)

**Pull request merged**
